"""Stage 4: test whether closing prices avoid round 50-RMB levels.

Descriptively, training-sample closes sit slightly farther from the nearest
50-RMB level than a uniform benchmark (mean distance ~12.78 vs 12.5), i.e. they
appear to *avoid* round numbers. But the distance series is highly persistent
(lag-1 autocorrelation ~0.94; the nearest level changes only ~133 times in the
sample), so a naive goodness-of-fit test that treats each day as independent
massively overstates significance.

This stage settles the question with a Monte Carlo null. Under the null there is
NO round-number preference: prices simply follow a process with the same return
behaviour as the real series. Null paths are generated by moving-block bootstrap
of the actual daily log returns, which preserves autocorrelation and fat tails
while destroying any link between price *level* and subsequent returns. For each
synthetic path we recompute the distance distribution; the empirical statistics
are then compared to the resulting null band.

Scope: this stage tests the distance distribution only. It does not study
support/resistance, next-day returns, or volatility, and it uses the training
window (2006-2020) only, leaving 2021+ held out. Inputs are read only.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd

try:
    import matplotlib.pyplot as plt
except ModuleNotFoundError:  # pragma: no cover
    plt = None


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
WORKSPACE_ROOT = PROJECT_ROOT.parent
DEFAULT_INPUT = (
    WORKSPACE_ROOT / "outputs" / "stage2_variable_construction" / "au9999_analysis_dataset.csv"
)
DEFAULT_OUTPUT_DIR = WORKSPACE_ROOT / "outputs" / "stage4_roundnumber_avoidance_test"

TRAIN_START = pd.Timestamp("2006-01-01")
TRAIN_END = pd.Timestamp("2020-12-31")
LEVEL_STEP = 50.0
HALF_STEP = LEVEL_STEP / 2.0
NEAR_THRESHOLDS = [2.5, 5.0, 7.5, 10.0]


@dataclass
class Config:
    source: Path = DEFAULT_INPUT
    output_dir: Path = DEFAULT_OUTPUT_DIR
    n_sim: int = 2000
    block_length: int = 20
    seed: int = 12345


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Monte Carlo test of round-50 avoidance")
    parser.add_argument("--source", default=str(DEFAULT_INPUT))
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--n-sim", type=int, default=2000)
    parser.add_argument("--block-length", type=int, default=20)
    parser.add_argument("--seed", type=int, default=12345)
    return parser.parse_args()




def repository_relative(path: Path) -> str:
    """Return a portable repository-relative path without exposing local folders."""
    try:
        return path.resolve().relative_to(WORKSPACE_ROOT.resolve()).as_posix()
    except ValueError:
        return path.name

def distance_to_level(prices: np.ndarray) -> np.ndarray:
    nearest = np.floor(prices / LEVEL_STEP + 0.5) * LEVEL_STEP
    return np.abs(prices - nearest)


def load_training_closes(source: Path) -> pd.DataFrame:
    df = pd.read_csv(source)
    for col in ("trade_date", "close_price"):
        if col not in df.columns:
            raise ValueError(f"Input is missing required column '{col}'.")
    df = df[["trade_date", "close_price"]].copy()
    df["trade_date"] = pd.to_datetime(df["trade_date"], errors="coerce")
    df["close_price"] = pd.to_numeric(df["close_price"], errors="coerce")
    df = df.sort_values("trade_date").reset_index(drop=True)
    train = df[(df["trade_date"] >= TRAIN_START) & (df["trade_date"] <= TRAIN_END)]
    train = train.dropna(subset=["trade_date", "close_price"])
    train = train[train["close_price"] > 0].reset_index(drop=True)
    return train


def empirical_stats(distances: np.ndarray) -> dict:
    n = len(distances)
    stats = {"mean_distance": float(distances.mean())}
    for thr in NEAR_THRESHOLDS:
        stats[f"prop_le_{thr}"] = float((distances <= thr).mean())
    counts, _ = np.histogram(distances, bins=np.arange(0, 26, 1))
    stats["bin_proportions"] = (counts / n).tolist()
    return stats


def simulate_null(returns: np.ndarray, start_price: float, n_close: int, config: Config) -> dict:
    """Moving-block bootstrap of log returns -> synthetic distance distributions."""
    rng = np.random.default_rng(config.seed)
    n_ret = len(returns)
    L = min(config.block_length, n_ret)
    n_needed = n_close - 1  # returns needed to build n_close prices from a fixed start
    n_blocks = int(np.ceil(n_needed / L))

    B = config.n_sim
    starts = rng.integers(0, n_ret - L + 1, size=(B, n_blocks))
    offsets = np.arange(L)
    idx = (starts[:, :, None] + offsets[None, None, :]).reshape(B, n_blocks * L)[:, :n_needed]
    sampled = returns[idx]  # (B, n_needed)

    log_start = np.log(start_price)
    log_prices = log_start + np.cumsum(sampled, axis=1)
    prices = np.exp(log_prices)
    prices = np.concatenate([np.full((B, 1), start_price), prices], axis=1)  # (B, n_close)

    dist = distance_to_level(prices)

    mean_dist = dist.mean(axis=1)
    props = {thr: (dist <= thr).mean(axis=1) for thr in NEAR_THRESHOLDS}
    bin_edges = np.arange(0, 26, 1)
    bin_props = np.stack(
        [np.histogram(dist[b], bins=bin_edges)[0] / n_close for b in range(B)], axis=0
    )  # (B, 25)

    return {
        "mean_distance": mean_dist,
        "props": props,
        "bin_props": bin_props,
        "block_length": L,
        "n_sim": B,
    }


def two_sided_p(sim: np.ndarray, observed: float) -> float:
    B = len(sim)
    ge = float((sim >= observed).sum())
    le = float((sim <= observed).sum())
    # +1 smoothing to avoid p=0 with finite simulations
    return float(min(1.0, 2.0 * min(ge + 1, le + 1) / (B + 1)))


def percentile_row(sim: np.ndarray, observed: float, name: str) -> dict:
    return {
        "statistic": name,
        "empirical": round(float(observed), 6),
        "null_median": round(float(np.median(sim)), 6),
        "null_p2.5": round(float(np.percentile(sim, 2.5)), 6),
        "null_p97.5": round(float(np.percentile(sim, 97.5)), 6),
        "empirical_percentile_in_null": round(float((sim < observed).mean() * 100), 2),
        "two_sided_p": round(two_sided_p(sim, observed), 4),
        "outside_95_null_band": bool(
            observed < np.percentile(sim, 2.5) or observed > np.percentile(sim, 97.5)
        ),
    }


def build_stat_table(emp: dict, null: dict) -> pd.DataFrame:
    rows = [percentile_row(null["mean_distance"], emp["mean_distance"], "mean_distance")]
    for thr in NEAR_THRESHOLDS:
        rows.append(percentile_row(null["props"][thr], emp[f"prop_le_{thr}"], f"prop_distance_le_{thr}"))
    return pd.DataFrame(rows)


def build_bin_band(emp: dict, null: dict) -> pd.DataFrame:
    bin_props = null["bin_props"]
    labels = [f"[{i},{i + 1})" for i in range(25)]
    return pd.DataFrame(
        {
            "distance_bin_yuan": labels,
            "empirical_proportion": np.round(emp["bin_proportions"], 6),
            "null_median": np.round(np.median(bin_props, axis=0), 6),
            "null_p2.5": np.round(np.percentile(bin_props, 2.5, axis=0), 6),
            "null_p97.5": np.round(np.percentile(bin_props, 97.5, axis=0), 6),
            "empirical_below_null_band": emp["bin_proportions"] < np.percentile(bin_props, 2.5, axis=0),
            "empirical_above_null_band": emp["bin_proportions"] > np.percentile(bin_props, 97.5, axis=0),
        }
    )


def save_band_plot(bin_band: pd.DataFrame, output_dir: Path) -> Path | None:
    if plt is None:
        return None
    out = output_dir / "distance_empirical_vs_null_band.png"
    x = np.arange(25) + 0.5
    fig, ax = plt.subplots(figsize=(9.5, 5.4))
    ax.fill_between(
        x,
        bin_band["null_p2.5"],
        bin_band["null_p97.5"],
        color="#B0B0B0",
        alpha=0.45,
        label="No-preference null band (95%)",
    )
    ax.plot(x, bin_band["null_median"], color="#555555", linewidth=1.2, linestyle="--", label="Null median")
    ax.plot(x, bin_band["empirical_proportion"], color="#D95F02", linewidth=2.2, marker="o", markersize=3, label="Empirical")
    ax.set_title("Distance to Nearest 50 RMB Level: Empirical vs No-Preference Null")
    ax.set_xlabel("Distance to nearest 50 RMB level (yuan)")
    ax.set_ylabel("Proportion of observations")
    ax.set_xlim(0, 25)
    ax.grid(axis="y", alpha=0.25)
    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(out, dpi=160)
    plt.close(fig)
    return out


def md_table(df: pd.DataFrame) -> str:
    cols = [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "| " + " | ".join(["---"] * len(cols)) + " |"]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(str(row[c]) for c in df.columns) + " |")
    return "\n".join(lines)


def interpret(stat_table: pd.DataFrame, bin_band: pd.DataFrame) -> str:
    mean_row = stat_table[stat_table["statistic"] == "mean_distance"].iloc[0]
    any_outside = bool(stat_table["outside_95_null_band"].any())
    zero_bin = bin_band.iloc[0]
    near_bins_below = int(bin_band.head(5)["empirical_below_null_band"].sum())

    if not any_outside:
        headline = (
            "The empirical distance statistics all fall INSIDE the 95% no-preference null band. "
            "The apparent avoidance of round 50-RMB levels is statistically indistinguishable from "
            "what a mechanical price process with the same return behaviour produces. We cannot claim "
            "a genuine round-number avoidance effect from this evidence."
        )
    else:
        headline = (
            "At least one empirical statistic falls OUTSIDE the 95% no-preference null band, so the "
            "avoidance is not fully explained by the mechanical null. This is suggestive but should be "
            "confirmed with an alternative null (e.g. Gaussian walk) and out-of-sample data before "
            "any effect is claimed."
        )
    return (
        f"{headline}\n\n"
        f"- Mean distance: empirical {mean_row['empirical']} vs null median {mean_row['null_median']} "
        f"(95% null band {mean_row['null_p2.5']} to {mean_row['null_p97.5']}), two-sided p = {mean_row['two_sided_p']}.\n"
        f"- Distance bin [0,1): empirical {zero_bin['empirical_proportion']} vs null median {zero_bin['null_median']} "
        f"(band {zero_bin['null_p2.5']} to {zero_bin['null_p97.5']}).\n"
        f"- Of the 5 bins nearest a level (0-5 yuan), {near_bins_below} sit below the null band."
    )


def write_report(config: Config, train: pd.DataFrame, null: dict, stat_table: pd.DataFrame, bin_band: pd.DataFrame, plot_path: Path | None) -> Path:
    out = config.output_dir / "roundnumber_avoidance_test_report.md"
    plot_line = f"![Empirical vs null band]({plot_path.name})\n" if plot_path else "_Plot unavailable (matplotlib not installed)._\n"
    report = f"""# Stage 4: Round-Number Avoidance Test

## Scope

This stage tests whether training-sample closing prices avoid round 50-RMB levels
beyond what a mechanical price process would produce. It uses the training window
{TRAIN_START.date()} to {TRAIN_END.date()} only; data from 2021 onward is held out.
It tests the distance distribution only, and does not study support/resistance,
next-day returns, volatility, or trading rules.

## Why a naive test is not enough

The distance-to-level series is highly persistent (lag-1 autocorrelation ~0.94;
the nearest 50-level changes only about 133 times across the sample). Treating
each day as an independent observation overstates significance. This stage instead
compares the empirical distance distribution to a Monte Carlo null.

## Null model

- Under the null, prices have NO round-number preference.
- Null paths start at the first training close and are built by moving-block
  bootstrap of the actual daily log returns.
- Block length: {null['block_length']} trading days (preserves short-run
  autocorrelation and fat tails while breaking any price-level/return link).
- Simulations: {null['n_sim']}. Seed: {config.seed} (reproducible).

## Input

- File: `{config.source.name}`
- Training observations: {len(train):,}
- Start price for null paths: {train['close_price'].iloc[0]}

## Statistic Comparison

{md_table(stat_table)}

`empirical_percentile_in_null` is where the empirical value sits within the null
distribution (50 = dead centre). `outside_95_null_band` is the decision flag.

## Per-Bin Empirical vs Null Band

{md_table(bin_band)}

## Chart

{plot_line}
## Interpretation

{interpret(stat_table, bin_band)}

## Caveats

- A single empirical path is compared to a null band; this is a parametric-style
  bootstrap test, not a large-sample asymptotic test.
- The block bootstrap preserves the marginal return distribution and short-run
  dependence but assumes returns are otherwise level-independent under the null.
- Failing to reject the null is not proof of no effect; it means this dataset and
  test do not provide evidence for one.
"""
    out.write_text(report, encoding="utf-8")
    return out


def run(config: Config) -> dict:
    if not config.source.exists():
        raise FileNotFoundError(f"Working dataset not found: {config.source}")
    config.output_dir.mkdir(parents=True, exist_ok=True)

    train = load_training_closes(config.source)
    closes = train["close_price"].to_numpy()
    n_close = len(closes)
    returns = np.diff(np.log(closes))

    emp_dist = distance_to_level(closes)
    emp = empirical_stats(emp_dist)

    null = simulate_null(returns, float(closes[0]), n_close, config)
    stat_table = build_stat_table(emp, null)
    bin_band = build_bin_band(emp, null)
    plot_path = save_band_plot(bin_band, config.output_dir)

    stat_table.to_csv(config.output_dir / "statistic_comparison.csv", index=False, encoding="utf-8-sig")
    bin_band.to_csv(config.output_dir / "per_bin_null_band.csv", index=False, encoding="utf-8-sig")
    report_path = write_report(config, train, null, stat_table, bin_band, plot_path)

    any_outside = bool(stat_table["outside_95_null_band"].any())
    summary = {
        "input_file": repository_relative(config.source),
        "training_observations": int(n_close),
        "n_sim": config.n_sim,
        "block_length": null["block_length"],
        "seed": config.seed,
        "empirical_mean_distance": round(emp["mean_distance"], 6),
        "any_statistic_outside_95_null_band": any_outside,
        "conclusion": (
            "avoidance NOT distinguishable from mechanical null"
            if not any_outside
            else "at least one statistic escapes the null band; confirm before claiming an effect"
        ),
        "report": repository_relative(report_path),
    }
    (config.output_dir / "test_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    return summary


def main() -> None:
    args = parse_args()
    config = Config(
        source=Path(args.source),
        output_dir=Path(args.output_dir),
        n_sim=args.n_sim,
        block_length=args.block_length,
        seed=args.seed,
    )
    print(json.dumps(run(config), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
